### ISSUE TITLE
1.1.5: sphinx fails

### ISSUE THREAD

**Issue by kloczek** [bitprophet/pytest-relaxed#17]
I'm trying to package your module as rpm packag and I need `pytest-relaxed` documentation and looks like it fails. I'm not sure is it sphinx issue or it something wrog with using sphinx here ..
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.1.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [ 50%] changelog
Extension error (releases):
Handler <function generate_changelog at 0x7f12829c1a60> for event 'doctree-read' threw an exception (exception: Call either Version('1.2.3') or Version(major=1, ...).)
```

**Comment by kloczek** [comment]
Looks like in 2.0.0 this still fails 😞 
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.3.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [ 50%] changelog
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/releases/__init__.py", line 612, in generate_changelog
    doctree.walk(changelog_visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 150, in walk
    if child.walk(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 150, in walk
    if child.walk(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 142, in walk
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2005, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.8/site-packages/releases/__init__.py", line 595, in visit_bullet_list
    releases, _ = construct_releases(node.children, self.app)
  File "/usr/lib/python3.8/site-packages/releases/__init__.py", line 521, in construct_releases
    construct_entry_without_release(focus, issues, manager, log, rest)
  File "/usr/lib/python3.8/site-packages/releases/__init__.py", line 405, in construct_entry_without_release
    focus.add_to_manager(manager)
  File "/usr/lib/python3.8/site-packages/releases/models.py", line 136, in add_to_manager
    families = [Version(str(x)) for x in manager]
  File "/usr/lib/python3.8/site-packages/releases/models.py", line 136, in <listcomp>
    families = [Version(str(x)) for x in manager]
  File "/usr/lib/python3.8/site-packages/releases/models.py", line 14, in __init__
    super(Version, self).__init__(version_string, partial)
  File "/usr/lib/python3.8/site-packages/semantic_version/base.py", line 102, in __init__
    raise ValueError("Call either Version('1.2.3') or Version(major=1, ...).")
ValueError: Call either Version('1.2.3') or Version(major=1, ...).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 307, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 326, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 433, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 454, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 510, in read_doc
    publisher.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 226, in publish
    self.apply_transforms()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 206, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 80, in apply_transforms
    super().apply_transforms()
  File "/usr/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 173, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 381, in apply
    self.app.emit('doctree-read', self.document)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 458, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function generate_changelog at 0x7fe81e8f9160> for event 'doctree-read' threw an exception (exception: Call either Version('1.2.3') or Version(major=1, ...).)

Extension error (releases):
Handler <function generate_changelog at 0x7fe81e8f9160> for event 'doctree-read' threw an exception (exception: Call either Version('1.2.3') or Version(major=1, ...).)
```
</details>

**Comment by kloczek** [comment]
Gentle ping ,. any update? 🤔 \
Just retested with python 3.9 and sphinx 7.2.6 and still fails.
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.2.6
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-pytest-relaxed.3 { changelog } /home/tkloczko/rpmbuild/BUILD/pytest-relaxed-2.0.1/docs/changelog.rst:5: WARNING: unknown node type: <release 2.0.1>
failed

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 363, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.9/site-packages/sphinx/util/display.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/sphinx/builders/manpage.py", line 103, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.9/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.9/site-packages/sphinx/writers/manpage.py", line 37, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 6 more times]
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 199, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.9/site-packages/sphinx/util/docutils.py", line 602, in dispatch_departure
    super().dispatch_departure(node)
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 2019, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 2041, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.manpage.ManualPageTranslator'> departing unknown node type: Release

Exception occurred:
  File "/usr/lib/python3.9/site-packages/docutils/nodes.py", line 2041, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.manpage.ManualPageTranslator'> departing unknown node type: Release
The full traceback has been saved in /tmp/sphinx-err-48al0trv.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
</details>
